name: Build and Release APKs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 安装 Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # gradlew 权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 恢复 keystore
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

    # 创建 signing.properties
    - name: Create signing properties
      run: |
        echo "STORE_FILE=../release.keystore" >> signing.properties
        echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> signing.properties
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> signing.properties

    # Build Release APK
    - name: Build Release APKs
      env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: ./gradlew assembleRelease

    # 重命名 APK
    - name: Rename APKs
      run: |
        mv mobile/build/outputs/apk/release/*.apk mobile-release.apk
        mv wear/build/outputs/apk/release/*.apk wear-release.apk

    # 创建 Release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        generate_release_notes: true
        files: |
          mobile-release.apk
          wear-release.apk
